const extraRecipes = [
    // CHINESE (10)
    {
        title: 'Kung Pao Chicken',
        description: 'Spicy, stir-fried Chinese dish made with cubes of chicken, peanuts, vegetables, and chili peppers.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '400',
        category: 'Dinner',
        tags: ['Chinese', 'Spicy', 'Chicken'],
        image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chicken breast', 'Peanuts', 'Dried chili peppers', 'Scallions', 'Soy sauce', 'Vinegar', 'Sugar'],
        instructions: ['Marinate chicken.', 'Stir-fry chicken until golden.', 'Add aromatics and peppers.', 'Add sauce and peanuts.', 'Serve with rice.'],
        rating: 4.7
    },
    {
        title: 'Sweet and Sour Pork',
        description: 'Deep-fried pork stir-fried with pineapple and peppers in a tangy sweet and sour sauce.',
        time: '45 min',
        difficulty: 'Medium',
        calories: '550',
        category: 'Dinner',
        tags: ['Chinese', 'Pork', 'Sweet'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Pork tenderloin', 'Pineapple chunks', 'Bell peppers', 'Onion', 'Ketchup', 'Vinegar', 'Sugar', 'Cornstarch'],
        instructions: ['Coat pork in batter and deep fry.', 'Stir-fry vegetables.', 'Make sauce.', 'Toss pork in sauce.', 'Serve hot.'],
        rating: 4.6
    },
    {
        title: 'Mapo Tofu',
        description: 'Tofu set in a spicy sauce, typically a thin, oily, and bright red suspension, based on douban and douchi.',
        time: '25 min',
        difficulty: 'Medium',
        calories: '300',
        category: 'Dinner',
        tags: ['Chinese', 'Spicy', 'Tofu', 'Vegetarian'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Silken tofu', 'Ground pork (optional)', 'Doubanjiang (chili bean paste)', 'Sichuan peppercorns', 'Scallions', 'Garlic'],
        instructions: ['Fry pork/meat substitute.', 'Add chili paste and aromatics.', 'Add broth and tofu.', 'Simmer.', 'Thicken with cornstarch.'],
        rating: 4.5
    },
    {
        title: 'Cantonese Chow Mein',
        description: 'Crispy pan-fried noodles topped with a savory stir-fry of meat and vegetables.',
        time: '30 min',
        difficulty: 'Easy',
        calories: '450',
        category: 'Lunch',
        tags: ['Chinese', 'Noodles', 'Quick'],
        image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Egg noodles', 'Bok choy', 'Chicken or Beef', 'Soy sauce', 'Oyster sauce', 'Ginger', 'Garlic'],
        instructions: ['Pan-fry noodles until crispy.', 'Stir-fry meat and veggies.', 'Make sauce.', 'Pour topping over noodles.'],
        rating: 4.4
    },
    {
        title: 'Peking Duck',
        description: 'Famous duck dish from Beijing that has been prepared since the Imperial era, characterized by its thin, crisp skin.',
        time: '120 min',
        difficulty: 'Hard',
        calories: '600',
        category: 'Dinner',
        tags: ['Chinese', 'Duck', 'Classic'],
        image: 'https://images.unsplash.com/photo-1632832066345-06b245413476?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Whole duck', 'Honey', 'Soy sauce', 'Five-spice powder', 'Pancakes', 'Hoisin sauce', 'Cucumber'],
        instructions: ['Air-dry duck.', 'Glaze with honey mixture.', 'Roast until skin is crispy.', 'Serve with pancakes and sauce.'],
        rating: 4.9
    },
    {
        title: 'Dim Sum: Siu Mai',
        description: 'Traditional open-topped steamed dumplings filled with pork and shrimp.',
        time: '60 min',
        difficulty: 'Hard',
        calories: '200',
        category: 'Lunch',
        tags: ['Chinese', 'Dim Sum', 'Appetizer'],
        image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c423c?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Ground pork', 'Shrimp', 'Wonton wrappers', 'Shiitake mushrooms', 'Soy sauce', 'Sesame oil'],
        instructions: ['Mix filling ingredients.', 'Place filling in wrappers.', 'Steam for 8-10 minutes.', 'Serve hot.'],
        rating: 4.8
    },
    {
        title: 'Hot Pot',
        description: 'A communal meal where ingredients are cooked in a simmering pot of soup stock at the table.',
        time: '90 min',
        difficulty: 'Easy',
        calories: '500',
        category: 'Dinner',
        tags: ['Chinese', 'Social', 'Soup'],
        image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Soup base', 'Thinly sliced beef', 'Lamb', 'Tofu', 'Mushrooms', 'Leafy greens', 'Noodles', 'Dipping sauces'],
        instructions: ['Prepare soup base.', 'Arrange raw ingredients on platters.', 'Cook ingredients in the pot at the table.', 'Dip in sauce and eat.'],
        rating: 5.0
    },
    {
        title: 'Wonton Soup',
        description: 'Delicate dumplings in a clear, savory broth.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '250',
        category: 'Lunch',
        tags: ['Chinese', 'Soup', 'Comfort'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Ground pork', 'Shrimp', 'Wonton wrappers', 'Chicken broth', 'Bok choy', 'Green onions'],
        instructions: ['Make wontons.', 'Boil broth.', 'Cook wontons in broth.', 'Add veggies and serve.'],
        rating: 4.6
    },
    {
        title: 'Yangzhou Fried Rice',
        description: 'Classic fried rice with egg, shrimp, pork, and peas.',
        time: '20 min',
        difficulty: 'Easy',
        calories: '400',
        category: 'Lunch',
        tags: ['Chinese', 'Rice', 'Quick'],
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb74b?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Cooked rice', 'Eggs', 'Shrimp', 'Char siu pork', 'Peas', 'Carrots', 'Soy sauce'],
        instructions: ['Scramble eggs.', 'Stir-fry meat and veggies.', 'Add rice and sauce.', 'Toss until heated through.'],
        rating: 4.7
    },
    {
        title: 'Spring Rolls',
        description: 'Crispy fried rolls filled with vegetables and sometimes meat.',
        time: '45 min',
        difficulty: 'Medium',
        calories: '150',
        category: 'Appetizer',
        tags: ['Chinese', 'Appetizer', 'Fried'],
        image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Spring roll wrappers', 'Cabbage', 'Carrots', 'Mushrooms', 'Glass noodles', 'Soy sauce'],
        instructions: ['Prepare filling.', 'Wrap in wrappers.', 'Deep fry until golden.', 'Serve with plum sauce.'],
        rating: 4.5
    },

    // INDIAN (20)
    {
        title: 'Butter Chicken',
        description: 'Chicken marinated in yogurt and spices, cooked in a velvety tomato cream sauce.',
        time: '50 min',
        difficulty: 'Medium',
        calories: '500',
        category: 'Dinner',
        tags: ['Indian', 'Curry', 'Chicken'],
        image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chicken thighs', 'Yogurt', 'Tomato puree', 'Cream', 'Butter', 'Garam masala', 'Fenugreek leaves'],
        instructions: ['Marinate chicken.', 'Cook chicken.', 'Make sauce with tomatoes and spices.', 'Add cream and butter.', 'Simmer chicken in sauce.'],
        rating: 4.9
    },
    {
        title: 'Palak Paneer',
        description: 'Cottage cheese cubes in a smooth, spiced spinach gravy.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '350',
        category: 'Dinner',
        tags: ['Indian', 'Vegetarian', 'Healthy'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Paneer', 'Spinach', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Cream', 'Cumin'],
        instructions: ['Blanch spinach and puree.', 'Fry paneer cubes.', 'Sauté aromatics.', 'Add spinach and spices.', 'Add paneer and cream.'],
        rating: 4.7
    },
    {
        title: 'Chana Masala',
        description: 'Spicy and savory chickpea curry.',
        time: '35 min',
        difficulty: 'Easy',
        calories: '300',
        category: 'Lunch',
        tags: ['Indian', 'Vegetarian', 'Vegan'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chickpeas', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Chana masala spice', 'Cilantro'],
        instructions: ['Sauté onion, ginger, garlic.', 'Add tomatoes and spices.', 'Add chickpeas and water.', 'Simmer.', 'Garnish with cilantro.'],
        rating: 4.6
    },
    {
        title: 'Chicken Biryani',
        description: 'Aromatic rice dish cooked with spiced chicken and herbs.',
        time: '90 min',
        difficulty: 'Hard',
        calories: '600',
        category: 'Dinner',
        tags: ['Indian', 'Rice', 'Chicken'],
        image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Basmati rice', 'Chicken', 'Yogurt', 'Fried onions', 'Saffron', 'Mint', 'Biryani masala'],
        instructions: ['Marinate chicken.', 'Par-boil rice.', 'Layer chicken and rice.', 'Dum cook (steam) on low heat.'],
        rating: 4.9
    },
    {
        title: 'Samosas',
        description: 'Fried pastry with a savory filling, such as spiced potatoes, onions, and peas.',
        time: '60 min',
        difficulty: 'Medium',
        calories: '250',
        category: 'Appetizer',
        tags: ['Indian', 'Snack', 'Vegetarian'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Flour', 'Potatoes', 'Peas', 'Cumin seeds', 'Garam masala', 'Oil'],
        instructions: ['Make dough.', 'Prepare filling.', 'Shape samosas.', 'Deep fry until golden.'],
        rating: 4.8
    },
    {
        title: 'Aloo Gobi',
        description: 'Dry curry made with potatoes and cauliflower.',
        time: '30 min',
        difficulty: 'Easy',
        calories: '200',
        category: 'Lunch',
        tags: ['Indian', 'Vegetarian', 'Vegan'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Potatoes', 'Cauliflower', 'Turmeric', 'Cumin', 'Coriander', 'Tomato'],
        instructions: ['Fry spices.', 'Add potatoes and cauliflower.', 'Cover and cook until tender.', 'Garnish with cilantro.'],
        rating: 4.5
    },
    {
        title: 'Dal Makhani',
        description: 'Whole black lentils cooked with butter and cream.',
        time: '120 min',
        difficulty: 'Medium',
        calories: '400',
        category: 'Dinner',
        tags: ['Indian', 'Vegetarian', 'Comfort'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Black lentils (Urad dal)', 'Kidney beans', 'Butter', 'Cream', 'Tomato puree', 'Ginger', 'Garlic'],
        instructions: ['Soak lentils overnight.', 'Pressure cook lentils.', 'Prepare masala.', 'Simmer lentils with masala and butter for hours.'],
        rating: 4.8
    },
    {
        title: 'Tandoori Chicken',
        description: 'Chicken marinated in yogurt and spices and roasted in a tandoor (or oven).',
        time: '45 min',
        difficulty: 'Medium',
        calories: '350',
        category: 'Dinner',
        tags: ['Indian', 'Chicken', 'Healthy'],
        image: 'https://images.unsplash.com/photo-1628294895950-98052523e036?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chicken legs', 'Yogurt', 'Lemon juice', 'Tandoori masala', 'Red chili powder', 'Ginger garlic paste'],
        instructions: ['Score chicken.', 'Marinate overnight.', 'Grill or bake at high heat.', 'Serve with mint chutney.'],
        rating: 4.7
    },
    {
        title: 'Rogan Josh',
        description: 'Aromatic lamb curry from Kashmir.',
        time: '90 min',
        difficulty: 'Hard',
        calories: '500',
        category: 'Dinner',
        tags: ['Indian', 'Lamb', 'Curry'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Lamb shoulder', 'Yogurt', 'Kashmiri chili', 'Fennel powder', 'Ginger powder', 'Mustard oil'],
        instructions: ['Brown the meat.', 'Add spices and yogurt.', 'Slow cook until tender.'],
        rating: 4.8
    },
    {
        title: 'Malai Kofta',
        description: 'Potato and paneer balls in a rich, creamy cashew gravy.',
        time: '60 min',
        difficulty: 'Hard',
        calories: '550',
        category: 'Dinner',
        tags: ['Indian', 'Vegetarian', 'Rich'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Potatoes', 'Paneer', 'Cashews', 'Cream', 'Tomato', 'Onion', 'Spices'],
        instructions: ['Make koftas (balls) and fry.', 'Make gravy with cashews and cream.', 'Add koftas before serving.'],
        rating: 4.9
    },
    {
        title: 'Garlic Naan',
        description: 'Leavened flatbread baked in a tandoor, topped with garlic and butter.',
        time: '60 min',
        difficulty: 'Medium',
        calories: '250',
        category: 'Side',
        tags: ['Indian', 'Bread', 'Side'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Flour', 'Yeast', 'Yogurt', 'Garlic', 'Butter', 'Cilantro'],
        instructions: ['Make dough and let rise.', 'Roll out.', 'Cook on hot skillet or in oven.', 'Brush with garlic butter.'],
        rating: 4.8
    },
    {
        title: 'Lamb Vindaloo',
        description: 'Spicy and tangy curry from Goa, influenced by Portuguese cuisine.',
        time: '60 min',
        difficulty: 'Medium',
        calories: '450',
        category: 'Dinner',
        tags: ['Indian', 'Spicy', 'Lamb'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Lamb', 'Vinegar', 'Garlic', 'Dried chilies', 'Cumin', 'Mustard seeds'],
        instructions: ['Marinate lamb in vinegar paste.', 'Cook onions and spices.', 'Add lamb and simmer until tender.'],
        rating: 4.6
    },
    {
        title: 'Vegetable Pakoras',
        description: 'Crispy fritters made with vegetables and chickpea flour batter.',
        time: '30 min',
        difficulty: 'Easy',
        calories: '200',
        category: 'Snack',
        tags: ['Indian', 'Snack', 'Fried'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chickpea flour (Besan)', 'Onion', 'Spinach', 'Potato', 'Spices', 'Oil'],
        instructions: ['Mix veggies with batter.', 'Drop spoonfuls into hot oil.', 'Fry until golden.'],
        rating: 4.5
    },
    {
        title: 'Chicken Korma',
        description: 'Mild, creamy curry made with yogurt, nuts, and spices.',
        time: '50 min',
        difficulty: 'Medium',
        calories: '480',
        category: 'Dinner',
        tags: ['Indian', 'Mild', 'Chicken'],
        image: 'https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chicken', 'Yogurt', 'Almonds/Cashews', 'Onion', 'Cardamom', 'Cream'],
        instructions: ['Marinate chicken.', 'Make nut paste.', 'Cook onions and spices.', 'Add chicken and simmer with yogurt/cream.'],
        rating: 4.7
    },
    {
        title: 'Matar Paneer',
        description: 'Peas and paneer in a tomato-based sauce.',
        time: '30 min',
        difficulty: 'Easy',
        calories: '320',
        category: 'Dinner',
        tags: ['Indian', 'Vegetarian', 'Quick'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Paneer', 'Peas', 'Tomato', 'Onion', 'Garam masala', 'Cream'],
        instructions: ['Fry paneer.', 'Make gravy.', 'Add peas and paneer.', 'Simmer.'],
        rating: 4.6
    },
    {
        title: 'Masala Dosa',
        description: 'Crispy fermented crepe stuffed with spiced potatoes.',
        time: '40 min',
        difficulty: 'Hard',
        calories: '300',
        category: 'Breakfast',
        tags: ['Indian', 'South Indian', 'Breakfast'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Rice', 'Urad dal', 'Potatoes', 'Onion', 'Mustard seeds', 'Turmeric'],
        instructions: ['Ferment batter overnight.', 'Make potato filling.', 'Spread batter on griddle.', 'Fill and roll.'],
        rating: 4.9
    },
    {
        title: 'Idli Sambar',
        description: 'Steamed rice cakes served with lentil vegetable stew.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '250',
        category: 'Breakfast',
        tags: ['Indian', 'South Indian', 'Healthy'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Rice', 'Urad dal', 'Toor dal', 'Vegetables', 'Sambar powder', 'Tamarind'],
        instructions: ['Steam idlis.', 'Cook lentils and veggies.', 'Add tamarind and spices to make sambar.'],
        rating: 4.8
    },
    {
        title: 'Pav Bhaji',
        description: 'Spiced vegetable mash served with buttered bread rolls.',
        time: '45 min',
        difficulty: 'Medium',
        calories: '400',
        category: 'Dinner',
        tags: ['Indian', 'Street Food', 'Vegetarian'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Potatoes', 'Peas', 'Cauliflower', 'Tomato', 'Pav Bhaji Masala', 'Butter', 'Bread rolls'],
        instructions: ['Boil and mash veggies.', 'Cook with spices and butter.', 'Toast bread.', 'Serve with onions and lemon.'],
        rating: 4.9
    },
    {
        title: 'Pani Puri',
        description: 'Hollow crispy balls filled with spiced water and potatoes.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '150',
        category: 'Snack',
        tags: ['Indian', 'Street Food', 'Fun'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Semolina puris', 'Mint', 'Cilantro', 'Green chilies', 'Tamarind', 'Potatoes', 'Chickpeas'],
        instructions: ['Make spicy water.', 'Make sweet chutney.', 'Prepare filling.', 'Assemble and eat immediately.'],
        rating: 5.0
    },
    {
        title: 'Gulab Jamun',
        description: 'Deep-fried milk solids soaked in rose-flavored sugar syrup.',
        time: '45 min',
        difficulty: 'Medium',
        calories: '300',
        category: 'Dessert',
        tags: ['Indian', 'Dessert', 'Sweet'],
        dietaryTags: ['Vegetarian'],
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Milk powder', 'Flour', 'Sugar', 'Rose water', 'Cardamom', 'Ghee'],
        instructions: ['Make dough.', 'Fry balls.', 'Soak in hot syrup.'],
        rating: 4.9
    },

    // THAI (20)
    {
        title: 'Pad Thai',
        description: 'Stir-fried rice noodle dish with eggs, peanuts, tofu, and bean sprouts.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '450',
        category: 'Dinner',
        tags: ['Thai', 'Noodles', 'Classic'],
        image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Rice noodles', 'Tamarind paste', 'Fish sauce', 'Palm sugar', 'Peanuts', 'Egg', 'Shrimp/Chicken'],
        instructions: ['Soak noodles.', 'Make sauce.', 'Stir-fry protein and egg.', 'Add noodles and sauce.', 'Top with peanuts.'],
        rating: 4.8
    },
    {
        title: 'Thai Green Curry',
        description: 'Spicy curry made with green chilies, coconut milk, and Thai basil.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '400',
        category: 'Dinner',
        tags: ['Thai', 'Curry', 'Spicy'],
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Green curry paste', 'Coconut milk', 'Chicken', 'Eggplant', 'Thai basil', 'Kaffir lime leaves'],
        instructions: ['Fry curry paste.', 'Add coconut milk.', 'Add chicken and veggies.', 'Simmer.', 'Garnish with basil.'],
        rating: 4.7
    },
    {
        title: 'Tom Yum Goong',
        description: 'Hot and sour shrimp soup with lemongrass, galangal, and lime leaves.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '200',
        category: 'Soup',
        tags: ['Thai', 'Soup', 'Spicy'],
        image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b485c?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Shrimp', 'Lemongrass', 'Galangal', 'Kaffir lime leaves', 'Chili paste', 'Lime juice', 'Mushrooms'],
        instructions: ['Boil broth with herbs.', 'Add mushrooms and shrimp.', 'Season with fish sauce and lime off heat.'],
        rating: 4.8
    },
    {
        title: 'Thai Red Curry',
        description: 'Rich and spicy curry with red chili paste and coconut milk.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '420',
        category: 'Dinner',
        tags: ['Thai', 'Curry', 'Spicy'],
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Red curry paste', 'Coconut milk', 'Duck or Chicken', 'Bamboo shoots', 'Thai basil'],
        instructions: ['Fry paste.', 'Add coconut milk.', 'Add meat and veggies.', 'Simmer.'],
        rating: 4.7
    },
    {
        title: 'Som Tum (Papaya Salad)',
        description: 'Spicy green papaya salad with lime, chili, and peanuts.',
        time: '20 min',
        difficulty: 'Easy',
        calories: '150',
        category: 'Salad',
        tags: ['Thai', 'Salad', 'Spicy'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Green papaya', 'Long beans', 'Tomatoes', 'Peanuts', 'Dried shrimp', 'Chili', 'Lime', 'Fish sauce'],
        instructions: ['Shred papaya.', 'Pound garlic and chili.', 'Add liquids.', 'Toss with papaya and veggies.'],
        rating: 4.9
    },
    {
        title: 'Massaman Curry',
        description: 'Mild, slightly sweet curry with potatoes and peanuts, influenced by Persian cuisine.',
        time: '60 min',
        difficulty: 'Medium',
        calories: '500',
        category: 'Dinner',
        tags: ['Thai', 'Curry', 'Mild'],
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Massaman paste', 'Coconut milk', 'Beef or Chicken', 'Potatoes', 'Peanuts', 'Onion', 'Tamarind'],
        instructions: ['Fry paste.', 'Add coconut milk and meat.', 'Simmer.', 'Add potatoes and peanuts.', 'Cook until tender.'],
        rating: 4.8
    },
    {
        title: 'Panang Curry',
        description: 'Thick, salty and sweet red curry with a nutty peanut flavor.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '450',
        category: 'Dinner',
        tags: ['Thai', 'Curry', 'Rich'],
        image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Panang paste', 'Coconut milk', 'Pork or Chicken', 'Kaffir lime leaves', 'Peanuts'],
        instructions: ['Fry paste.', 'Add coconut milk.', 'Add meat.', 'Simmer until thick.'],
        rating: 4.7
    },
    {
        title: 'Mango Sticky Rice',
        description: 'Sweet sticky rice served with fresh mango and coconut cream.',
        time: '40 min',
        difficulty: 'Medium',
        calories: '350',
        category: 'Dessert',
        tags: ['Thai', 'Dessert', 'Sweet'],
        dietaryTags: ['Vegetarian', 'Vegan'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Glutinous rice', 'Coconut milk', 'Sugar', 'Ripe mango', 'Mung beans'],
        instructions: ['Steam rice.', 'Mix coconut milk and sugar.', 'Stir into rice.', 'Serve with mango slices.'],
        rating: 5.0
    },
    {
        title: 'Thai Fried Rice',
        description: 'Fried rice with jasmine rice, egg, onion, and choice of meat.',
        time: '20 min',
        difficulty: 'Easy',
        calories: '400',
        category: 'Lunch',
        tags: ['Thai', 'Rice', 'Quick'],
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb74b?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Jasmine rice', 'Egg', 'Onion', 'Tomato', 'Chicken/Shrimp', 'Soy sauce', 'Fish sauce'],
        instructions: ['Scramble egg.', 'Stir-fry meat and veggies.', 'Add rice and sauces.', 'Toss well.'],
        rating: 4.6
    },
    {
        title: 'Chicken Satay',
        description: 'Grilled chicken skewers served with peanut dipping sauce.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '300',
        category: 'Appetizer',
        tags: ['Thai', 'Appetizer', 'Grilled'],
        image: 'https://images.unsplash.com/photo-1532636875304-0c89119d9b4d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Chicken breast', 'Turmeric', 'Coconut milk', 'Peanut butter', 'Curry paste'],
        instructions: ['Marinate chicken.', 'Thread on skewers.', 'Grill.', 'Make peanut sauce.', 'Serve.'],
        rating: 4.8
    },
    {
        title: 'Tom Kha Gai',
        description: 'Creamy coconut chicken soup with galangal.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '350',
        category: 'Soup',
        tags: ['Thai', 'Soup', 'Creamy'],
        image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b485c?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Coconut milk', 'Chicken', 'Galangal', 'Lemongrass', 'Mushrooms', 'Lime juice'],
        instructions: ['Simmer coconut milk with herbs.', 'Add chicken and mushrooms.', 'Season with fish sauce and lime.'],
        rating: 4.9
    },
    {
        title: 'Larb Gai',
        description: 'Spicy minced chicken salad with mint, lime, and toasted rice powder.',
        time: '20 min',
        difficulty: 'Easy',
        calories: '200',
        category: 'Salad',
        tags: ['Thai', 'Salad', 'Healthy'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Minced chicken', 'Lime juice', 'Fish sauce', 'Chili powder', 'Mint', 'Toasted rice powder'],
        instructions: ['Cook chicken.', 'Toss with dressing and herbs.', 'Serve with lettuce.'],
        rating: 4.7
    },
    {
        title: 'Pad See Ew',
        description: 'Stir-fried wide rice noodles with soy sauce, egg, and Chinese broccoli.',
        time: '25 min',
        difficulty: 'Medium',
        calories: '450',
        category: 'Dinner',
        tags: ['Thai', 'Noodles', 'Comfort'],
        image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Wide rice noodles', 'Dark soy sauce', 'Egg', 'Chinese broccoli', 'Chicken/Beef', 'Garlic'],
        instructions: ['Stir-fry meat and garlic.', 'Add noodles and broccoli.', 'Add sauce and egg.', 'Toss until caramelized.'],
        rating: 4.8
    },
    {
        title: 'Khao Soi',
        description: 'Northern Thai coconut curry noodle soup.',
        time: '50 min',
        difficulty: 'Medium',
        calories: '500',
        category: 'Dinner',
        tags: ['Thai', 'Soup', 'Curry'],
        image: 'https://images.unsplash.com/photo-1548943487-a2e4e43b485c?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Egg noodles', 'Curry paste', 'Coconut milk', 'Chicken', 'Mustard greens', 'Crispy noodles'],
        instructions: ['Make curry soup base.', 'Boil noodles.', 'Serve soup over noodles.', 'Top with crispy noodles.'],
        rating: 4.9
    },
    {
        title: 'Thai Fish Cakes',
        description: 'Fried fish patties flavored with red curry paste and kaffir lime leaves.',
        time: '30 min',
        difficulty: 'Medium',
        calories: '250',
        category: 'Appetizer',
        tags: ['Thai', 'Appetizer', 'Seafood'],
        image: 'https://images.unsplash.com/photo-1532636875304-0c89119d9b4d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['White fish', 'Red curry paste', 'Green beans', 'Kaffir lime leaves', 'Egg'],
        instructions: ['Blend fish with paste.', 'Mix in beans.', 'Form patties.', 'Deep fry.'],
        rating: 4.6
    },
    {
        title: 'Pad Krapow Gai',
        description: 'Spicy stir-fried chicken with holy basil, served with a fried egg.',
        time: '15 min',
        difficulty: 'Easy',
        calories: '400',
        category: 'Lunch',
        tags: ['Thai', 'Spicy', 'Quick'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Minced chicken', 'Holy basil', 'Chili', 'Garlic', 'Soy sauce', 'Egg'],
        instructions: ['Fry garlic and chili.', 'Add chicken.', 'Add sauces and basil.', 'Serve over rice with fried egg.'],
        rating: 5.0
    },
    {
        title: 'Pineapple Fried Rice',
        description: 'Fried rice with pineapple, curry powder, raisins, and cashews.',
        time: '25 min',
        difficulty: 'Easy',
        calories: '420',
        category: 'Lunch',
        tags: ['Thai', 'Rice', 'Sweet'],
        image: 'https://images.unsplash.com/photo-1603133872878-684f208fb74b?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Rice', 'Pineapple', 'Curry powder', 'Cashews', 'Raisins', 'Shrimp/Chicken'],
        instructions: ['Stir-fry ingredients.', 'Add rice and curry powder.', 'Serve in pineapple shell (optional).'],
        rating: 4.7
    },
    {
        title: 'Thai Iced Tea',
        description: 'Sweet, creamy, and spiced orange tea.',
        time: '10 min',
        difficulty: 'Easy',
        calories: '150',
        category: 'Beverage',
        tags: ['Thai', 'Drink', 'Sweet'],
        image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Thai tea mix', 'Sugar', 'Condensed milk', 'Evaporated milk', 'Ice'],
        instructions: ['Brew tea.', 'Stir in sugar and condensed milk.', 'Pour over ice.', 'Top with evaporated milk.'],
        rating: 4.9
    },
    {
        title: 'Sticky Rice with Custard',
        description: 'Sweet sticky rice topped with Thai egg custard.',
        time: '50 min',
        difficulty: 'Medium',
        calories: '300',
        category: 'Dessert',
        tags: ['Thai', 'Dessert', 'Sweet'],
        image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Glutinous rice', 'Coconut milk', 'Eggs', 'Palm sugar', 'Pandan leaves'],
        instructions: ['Steam rice with coconut milk.', 'Steam egg custard.', 'Serve together.'],
        rating: 4.6
    },
    {
        title: 'Thai Omelette (Kai Jeow)',
        description: 'Crispy, fluffy omelette usually served over rice.',
        time: '10 min',
        difficulty: 'Easy',
        calories: '250',
        category: 'Breakfast',
        tags: ['Thai', 'Breakfast', 'Quick'],
        image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?auto=format&fit=crop&w=800&q=80',
        ingredients: ['Eggs', 'Fish sauce', 'Lime juice', 'Oil', 'Green onions'],
        instructions: ['Beat eggs with seasonings.', 'Deep fry in hot oil until puffy and crispy.'],
        rating: 4.7
    }
];

module.exports = extraRecipes;
